name: dino
description: Yet another T-Rex clone, this time simplified to showcase flame for beginners.

version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
  assets:
   - assets/images/dino.png
