image: node:9.4.0

stages:
  - test
  - deploy

Test:
  stage: test
  before_script: 
    - npm install 
  script:
    - npm test

Deploy:
  stage: deploy
  only:
    - master
  before_script:
    - npm install -g serverless
    - npm install --production
    - echo -e "MONGO_HOST=$MONGO_HOST" > .env
    - echo -e "MONGO_USER=$MONGO_USER" >> .env
    - echo -e "MONGO_PASSWORD=$MONGO_PASSWORD" >> .env
    - echo -e "MONGO_PORT=$MONGO_PORT" >> .env
    - echo -e "MONGO_DB=$MONGO_DB" >> .env
  script:
    - serverless deploy